openapi: 3.0.0
info:
  title: webservice_sindy
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /regis:
    post:
      tags:
        - default
      summary: regis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 1
                username: sindy
                email: sindy@example.com
                password: securepassword123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: sindymaulina
                password: securepassword123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /kelas:
    get:
      tags:
        - default
      summary: kelas
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: kelas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama_kelas: pemograman
                semester: 4
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /kelas/{id}:
    put:
      tags:
        - default
      summary: kelas
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the class
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama_kelas: Kelas Diperbarui
                semester: 2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: kelas
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the class
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mahasiswa:
    post:
      tags:
        - default
      summary: mahasiswa
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: sindy maulina
                nim: '12345679'
                jurusan: Teknik Informatika
                user_id: 2
                kelas_id: 2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: mahasiswa
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mahasiswa/{id}:
    put:
      tags:
        - default
      summary: mahasiswa
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the student
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: sindy maulina
                nim: '12345610'
                jurusan: Teknik Informatika
                user_id: 2
                kelas_id: 2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: mahasiswa
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the student
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
